/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author PabloCass
 */
public class Menu_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Inicial
     */
    public Menu_Inicial() {
        initComponents();
        
    }

    int imagem = 0;
    
    URL url1 = this.getClass().getResource("/Imagens_Tabuleiro/tabuleiroTeste.jpg");
    URL url2 = this.getClass().getResource("/Imagens_Tabuleiro/tabuleiroTeste11.png");
    
    ImageIcon img = new ImageIcon(url1);
    ImageIcon img2 = new ImageIcon(url2);
    
    void alterarImagens() throws InterruptedException{
        
        if(imagem == 0){
            
            Thread.sleep(200);
            Imagens_Abertura.setIcon(img);
            Thread.sleep(2000);
            Imagens_Abertura.setIcon(img2);
        }        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Efeito3 = new javax.swing.JPanel();
        Efeito2 = new javax.swing.JPanel();
        Painel_abertura = new javax.swing.JPanel();
        Abertura = new javax.swing.JLabel();
        Painel_Meio_Jogo = new javax.swing.JPanel();
        MeioJogo = new javax.swing.JLabel();
        Painel_Final = new javax.swing.JPanel();
        Final = new javax.swing.JLabel();
        Painel_Tabuleiro = new javax.swing.JPanel();
        Tabuleiro = new javax.swing.JLabel();
        Painel_sair = new javax.swing.JPanel();
        Sair = new javax.swing.JLabel();
        Efeito1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        Abertura_Painel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Imagens_Abertura = new javax.swing.JLabel();
        Imagens_Abertura1 = new javax.swing.JLabel();
        Imagens_Abertura2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Meio_Jogo_Painel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Meio_jogo = new javax.swing.JLabel();
        Meio_Jogo2 = new javax.swing.JLabel();
        Meio_Jogo3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Final_Painel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Meio_jogo1 = new javax.swing.JLabel();
        Meio_Jogo4 = new javax.swing.JLabel();
        Meio_Jogo5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(9, 15, 20));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Snott", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("s");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 70, 80);

        jLabel5.setFont(new java.awt.Font("Snott", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Q");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 80);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Snott", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Alpha");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(80, 40, 130, 80);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 240, 150);

        jPanel5.setBackground(new java.awt.Color(9, 15, 20));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(null);

        Efeito3.setBackground(new java.awt.Color(9, 15, 20));
        Efeito3.setLayout(null);
        jPanel5.add(Efeito3);
        Efeito3.setBounds(180, 230, 10, 10);

        Efeito2.setBackground(new java.awt.Color(9, 15, 20));
        Efeito2.setLayout(null);
        jPanel5.add(Efeito2);
        Efeito2.setBounds(180, 140, 10, 10);

        Painel_abertura.setBackground(new java.awt.Color(9, 15, 20));
        Painel_abertura.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Painel_abertura.setLayout(null);

        Abertura.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        Abertura.setForeground(new java.awt.Color(255, 102, 0));
        Abertura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Abertura.setText("Abertura");
        Abertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AberturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AberturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AberturaMouseExited(evt);
            }
        });
        Painel_abertura.add(Abertura);
        Abertura.setBounds(0, 0, 160, 70);

        jPanel5.add(Painel_abertura);
        Painel_abertura.setBounds(20, 20, 160, 70);

        Painel_Meio_Jogo.setBackground(new java.awt.Color(9, 15, 20));
        Painel_Meio_Jogo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Painel_Meio_Jogo.setLayout(null);

        MeioJogo.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        MeioJogo.setForeground(new java.awt.Color(255, 102, 0));
        MeioJogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MeioJogo.setText("Meio jogo");
        MeioJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MeioJogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MeioJogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MeioJogoMouseExited(evt);
            }
        });
        Painel_Meio_Jogo.add(MeioJogo);
        MeioJogo.setBounds(0, 0, 160, 70);

        jPanel5.add(Painel_Meio_Jogo);
        Painel_Meio_Jogo.setBounds(20, 110, 160, 70);

        Painel_Final.setBackground(new java.awt.Color(9, 15, 20));
        Painel_Final.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Painel_Final.setLayout(null);

        Final.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        Final.setForeground(new java.awt.Color(255, 102, 0));
        Final.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Final.setText("Final");
        Final.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FinalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FinalMouseExited(evt);
            }
        });
        Painel_Final.add(Final);
        Final.setBounds(0, 0, 160, 70);

        jPanel5.add(Painel_Final);
        Painel_Final.setBounds(20, 200, 160, 70);

        Painel_Tabuleiro.setBackground(new java.awt.Color(9, 15, 20));
        Painel_Tabuleiro.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Painel_Tabuleiro.setLayout(null);

        Tabuleiro.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        Tabuleiro.setForeground(new java.awt.Color(255, 102, 0));
        Tabuleiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tabuleiro.setText("Jogar");
        Tabuleiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabuleiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabuleiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TabuleiroMouseExited(evt);
            }
        });
        Painel_Tabuleiro.add(Tabuleiro);
        Tabuleiro.setBounds(0, 0, 160, 70);

        jPanel5.add(Painel_Tabuleiro);
        Painel_Tabuleiro.setBounds(20, 290, 160, 70);

        Painel_sair.setBackground(new java.awt.Color(9, 15, 20));
        Painel_sair.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        Painel_sair.setLayout(null);

        Sair.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 102, 0));
        Sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SairMouseExited(evt);
            }
        });
        Painel_sair.add(Sair);
        Sair.setBounds(0, 0, 160, 70);

        jPanel5.add(Painel_sair);
        Painel_sair.setBounds(20, 380, 160, 70);

        Efeito1.setBackground(new java.awt.Color(9, 15, 20));
        Efeito1.setLayout(null);
        jPanel5.add(Efeito1);
        Efeito1.setBounds(180, 50, 10, 10);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(20, 160, 200, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 240, 650);

        jPanel2.setBackground(new java.awt.Color(53, 114, 114));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENXADRÍSTICO | IFRN-JC");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(170, 80, 580, 60);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROJETO DE SOFTWARE ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 580, 60);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 100, 160, 20);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(590, 40, 170, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(240, 0, 760, 150);

        Abertura_Painel.setBackground(new java.awt.Color(52, 57, 57));
        Abertura_Painel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("e por fim, conectar as torres.");
        Abertura_Painel.add(jLabel6);
        jLabel6.setBounds(10, 100, 740, 50);

        jLabel8.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("tram grandes conhecimentos através de preparações. Para completar a");
        Abertura_Painel.add(jLabel8);
        jLabel8.setBounds(10, 40, 740, 50);

        jLabel9.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("fase da abertura, o jogador deve desenvolver suas peças, fazer o roque");
        Abertura_Painel.add(jLabel9);
        jLabel9.setBounds(10, 70, 740, 50);

        jPanel3.setBackground(new java.awt.Color(40, 45, 46));
        jPanel3.setLayout(null);

        Imagens_Abertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/TorreConectadas.jpg"))); // NOI18N
        Imagens_Abertura.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Imagens_Abertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagens_AberturaMouseClicked(evt);
            }
        });
        Imagens_Abertura.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Imagens_AberturaComponentShown(evt);
            }
        });
        jPanel3.add(Imagens_Abertura);
        Imagens_Abertura.setBounds(520, 60, 200, 200);

        Imagens_Abertura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/Ruy-Lopes.jpg"))); // NOI18N
        Imagens_Abertura1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Imagens_Abertura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagens_Abertura1MouseClicked(evt);
            }
        });
        Imagens_Abertura1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Imagens_Abertura1ComponentShown(evt);
            }
        });
        jPanel3.add(Imagens_Abertura1);
        Imagens_Abertura1.setBounds(40, 60, 200, 200);

        Imagens_Abertura2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/Roque.jpg"))); // NOI18N
        Imagens_Abertura2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Imagens_Abertura2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Imagens_Abertura2MouseClicked(evt);
            }
        });
        Imagens_Abertura2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Imagens_Abertura2ComponentShown(evt);
            }
        });
        jPanel3.add(Imagens_Abertura2);
        Imagens_Abertura2.setBounds(280, 60, 200, 200);

        jLabel7.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Torres conectadas");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(520, 270, 200, 30);

        jLabel19.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 204, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Desenvolvimento das peças");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(40, 270, 200, 30);

        jLabel20.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Roque");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(280, 270, 200, 30);

        Abertura_Painel.add(jPanel3);
        jPanel3.setBounds(0, 160, 760, 340);

        jLabel18.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Momento inicial de uma partida de xadrez, onde os jogadores demons-");
        Abertura_Painel.add(jLabel18);
        jLabel18.setBounds(10, 10, 740, 50);

        jDesktopPane1.add(Abertura_Painel);
        Abertura_Painel.setBounds(0, 0, 760, 500);

        Meio_Jogo_Painel.setBackground(new java.awt.Color(52, 57, 57));
        Meio_Jogo_Painel.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(40, 45, 46));
        jPanel6.setLayout(null);

        Meio_jogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/Meio-jogo.2.jpg"))); // NOI18N
        Meio_jogo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_jogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_jogoMouseClicked(evt);
            }
        });
        Meio_jogo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_jogoComponentShown(evt);
            }
        });
        jPanel6.add(Meio_jogo);
        Meio_jogo.setBounds(520, 60, 200, 200);

        Meio_Jogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/Meio-jogo.1jpg.jpg"))); // NOI18N
        Meio_Jogo2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_Jogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_Jogo2MouseClicked(evt);
            }
        });
        Meio_Jogo2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_Jogo2ComponentShown(evt);
            }
        });
        jPanel6.add(Meio_Jogo2);
        Meio_Jogo2.setBounds(40, 60, 200, 200);

        Meio_Jogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/Meio-jogo.jpg"))); // NOI18N
        Meio_Jogo3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_Jogo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_Jogo3MouseClicked(evt);
            }
        });
        Meio_Jogo3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_Jogo3ComponentShown(evt);
            }
        });
        jPanel6.add(Meio_Jogo3);
        Meio_Jogo3.setBounds(280, 60, 200, 200);

        jLabel21.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 204, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Exemplo 3");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(520, 270, 200, 30);

        jLabel22.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 204, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Exemplo 1");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(40, 270, 200, 30);

        jLabel23.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 204, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Exemplo 2");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(280, 270, 200, 30);

        Meio_Jogo_Painel.add(jPanel6);
        jPanel6.setBounds(0, 160, 760, 340);

        jLabel10.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("para o desenvolvimento da partida.");
        Meio_Jogo_Painel.add(jLabel10);
        jLabel10.setBounds(10, 100, 740, 50);

        jLabel11.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Momento na partida onde uma quantidade de peças já possui ");
        Meio_Jogo_Painel.add(jLabel11);
        jLabel11.setBounds(10, 10, 740, 50);

        jLabel12.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("um grau de desenvolvimento considerável. Deve-se pensar em uma ");
        Meio_Jogo_Painel.add(jLabel12);
        jLabel12.setBounds(10, 40, 740, 50);

        jLabel13.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("estratégia para derrotar o oponente, sendo assim, é uma fase crucial ");
        Meio_Jogo_Painel.add(jLabel13);
        jLabel13.setBounds(10, 70, 740, 50);

        jDesktopPane1.add(Meio_Jogo_Painel);
        Meio_Jogo_Painel.setBounds(0, 0, 760, 500);

        Final_Painel.setBackground(new java.awt.Color(52, 57, 57));
        Final_Painel.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(40, 45, 46));
        jPanel7.setLayout(null);

        Meio_jogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/final3.jpg"))); // NOI18N
        Meio_jogo1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_jogo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_jogo1MouseClicked(evt);
            }
        });
        Meio_jogo1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_jogo1ComponentShown(evt);
            }
        });
        jPanel7.add(Meio_jogo1);
        Meio_jogo1.setBounds(520, 60, 200, 200);

        Meio_Jogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/final.jpg"))); // NOI18N
        Meio_Jogo4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_Jogo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_Jogo4MouseClicked(evt);
            }
        });
        Meio_Jogo4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_Jogo4ComponentShown(evt);
            }
        });
        jPanel7.add(Meio_Jogo4);
        Meio_Jogo4.setBounds(40, 60, 200, 200);

        Meio_Jogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Outras_Imagens/final2.jpg"))); // NOI18N
        Meio_Jogo5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        Meio_Jogo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Meio_Jogo5MouseClicked(evt);
            }
        });
        Meio_Jogo5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Meio_Jogo5ComponentShown(evt);
            }
        });
        jPanel7.add(Meio_Jogo5);
        Meio_Jogo5.setBounds(280, 60, 200, 200);

        jLabel24.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 204, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Final: Peões vs Peões");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(520, 270, 200, 30);

        jLabel25.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 204, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Final: Mate de Dama e Torre");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(40, 270, 200, 30);

        jLabel26.setFont(new java.awt.Font("Steinem", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 204, 102));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Final: Torre vs Peões");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(280, 270, 200, 30);

        Final_Painel.add(jPanel7);
        jPanel7.setBounds(0, 160, 760, 340);

        jLabel14.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("provavelmente causar a promoção de um deles.");
        Final_Painel.add(jLabel14);
        jLabel14.setBounds(10, 100, 740, 50);

        jLabel15.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Momento final da partida, há poucas peças no tabuleiro. Fase onde os  ");
        Final_Painel.add(jLabel15);
        jLabel15.setBounds(10, 10, 740, 50);

        jLabel16.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("peões ganham grande importância, assim como o rei, sendo cada vez");
        Final_Painel.add(jLabel16);
        jLabel16.setBounds(10, 40, 740, 50);

        jLabel17.setFont(new java.awt.Font("Steinem", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("mais levado para o centro do tabuleiro, afim de proteger seus peões, e");
        Final_Painel.add(jLabel17);
        jLabel17.setBounds(10, 70, 740, 50);

        jDesktopPane1.add(Final_Painel);
        Final_Painel.setBounds(0, 0, 760, 500);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(240, 150, 760, 500);

        setSize(new java.awt.Dimension(1000, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_SairMouseClicked

    private void AberturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AberturaMouseEntered
        
        Painel_abertura.setBackground(new Color(20,28,36));
        
    }//GEN-LAST:event_AberturaMouseEntered

    private void MeioJogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeioJogoMouseEntered
        Painel_Meio_Jogo.setBackground(new Color(20,28,36));
    }//GEN-LAST:event_MeioJogoMouseEntered

    private void FinalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalMouseEntered
        Painel_Final.setBackground(new Color(20,28,36));
    }//GEN-LAST:event_FinalMouseEntered

    private void TabuleiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabuleiroMouseClicked
    
        dispose();
        Tabuleiro tab = new Tabuleiro();
        tab.setVisible(true);
        
        
    }//GEN-LAST:event_TabuleiroMouseClicked

    private void SairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseEntered
        Painel_sair.setBackground(new Color(20,28,36));
    }//GEN-LAST:event_SairMouseEntered

    private void AberturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AberturaMouseExited
        Painel_abertura.setBackground(new Color(9,15,20));
    }//GEN-LAST:event_AberturaMouseExited

    private void MeioJogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeioJogoMouseExited
        Painel_Meio_Jogo.setBackground(new Color(9,15,20));
    }//GEN-LAST:event_MeioJogoMouseExited

    private void FinalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalMouseExited
        Painel_Final.setBackground(new Color(9,15,20));
    }//GEN-LAST:event_FinalMouseExited

    private void TabuleiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabuleiroMouseEntered
        Painel_Tabuleiro.setBackground(new Color(20,28,36));
    }//GEN-LAST:event_TabuleiroMouseEntered

    private void TabuleiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabuleiroMouseExited
        Painel_Tabuleiro.setBackground(new Color(9,15,20));
    }//GEN-LAST:event_TabuleiroMouseExited

    private void SairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseExited
        Painel_sair.setBackground(new Color(9,15,20));
    }//GEN-LAST:event_SairMouseExited

    private void AberturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AberturaMouseClicked
        
        Efeito1.setBackground(new Color(153,255,102));
        Efeito2.setBackground(new Color(9,15,20));
        Efeito3.setBackground(new Color(9,15,20));
        Abertura_Painel.setVisible(true);
        Meio_Jogo_Painel.setVisible(false);
        Final_Painel.setVisible(false);
    }//GEN-LAST:event_AberturaMouseClicked

    private void MeioJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MeioJogoMouseClicked
        
        Efeito2.setBackground(new Color(153,255,102));
        Efeito1.setBackground(new Color(9,15,20));
        Efeito3.setBackground(new Color(9,15,20));
        Abertura_Painel.setVisible(false);
        Meio_Jogo_Painel.setVisible(true);
        Final_Painel.setVisible(false);;
    }//GEN-LAST:event_MeioJogoMouseClicked

    private void FinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalMouseClicked
        
        Efeito3.setBackground(new Color(153,255,102));
        Efeito2.setBackground(new Color(9,15,20));
        Efeito1.setBackground(new Color(9,15,20));
        Abertura_Painel.setVisible(false);
        Meio_Jogo_Painel.setVisible(false);
        Final_Painel.setVisible(true);
    }//GEN-LAST:event_FinalMouseClicked

    private void Imagens_AberturaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Imagens_AberturaComponentShown
        
    }//GEN-LAST:event_Imagens_AberturaComponentShown

    private void Imagens_AberturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagens_AberturaMouseClicked
        try {
            alterarImagens();
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu_Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Imagens_AberturaMouseClicked

    private void Imagens_Abertura1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagens_Abertura1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagens_Abertura1MouseClicked

    private void Imagens_Abertura1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Imagens_Abertura1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagens_Abertura1ComponentShown

    private void Imagens_Abertura2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Imagens_Abertura2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagens_Abertura2MouseClicked

    private void Imagens_Abertura2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Imagens_Abertura2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Imagens_Abertura2ComponentShown

    private void Meio_jogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_jogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_jogoMouseClicked

    private void Meio_jogoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_jogoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_jogoComponentShown

    private void Meio_Jogo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_Jogo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo2MouseClicked

    private void Meio_Jogo2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_Jogo2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo2ComponentShown

    private void Meio_Jogo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_Jogo3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo3MouseClicked

    private void Meio_Jogo3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_Jogo3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo3ComponentShown

    private void Meio_jogo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_jogo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_jogo1MouseClicked

    private void Meio_jogo1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_jogo1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_jogo1ComponentShown

    private void Meio_Jogo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_Jogo4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo4MouseClicked

    private void Meio_Jogo4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_Jogo4ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo4ComponentShown

    private void Meio_Jogo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Meio_Jogo5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo5MouseClicked

    private void Meio_Jogo5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Meio_Jogo5ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Meio_Jogo5ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abertura;
    private javax.swing.JPanel Abertura_Painel;
    private javax.swing.JPanel Efeito1;
    private javax.swing.JPanel Efeito2;
    private javax.swing.JPanel Efeito3;
    private javax.swing.JLabel Final;
    private javax.swing.JPanel Final_Painel;
    private javax.swing.JLabel Imagens_Abertura;
    private javax.swing.JLabel Imagens_Abertura1;
    private javax.swing.JLabel Imagens_Abertura2;
    private javax.swing.JLabel MeioJogo;
    private javax.swing.JLabel Meio_Jogo2;
    private javax.swing.JLabel Meio_Jogo3;
    private javax.swing.JLabel Meio_Jogo4;
    private javax.swing.JLabel Meio_Jogo5;
    private javax.swing.JPanel Meio_Jogo_Painel;
    private javax.swing.JLabel Meio_jogo;
    private javax.swing.JLabel Meio_jogo1;
    private javax.swing.JPanel Painel_Final;
    private javax.swing.JPanel Painel_Meio_Jogo;
    private javax.swing.JPanel Painel_Tabuleiro;
    private javax.swing.JPanel Painel_abertura;
    private javax.swing.JPanel Painel_sair;
    private javax.swing.JLabel Sair;
    private javax.swing.JLabel Tabuleiro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
